server:
  port: 8085

# 可视化平台的用户名和密码
admin:
  username: admin
  password: 123456

spring:

  #thymeleaf模板引擎
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    mode: LEGACYHTML5
    cache: false
